### ISSUE TITLE
All the terms assigned to the attributes are displayed on the side bar

### ISSUE THREAD

**Issue by ashika123** [ajency/Coopstore#114]
![terms on side bar](https://cloud.githubusercontent.com/assets/9797052/7064909/122f47dc-ded0-11e4-8870-caa540569f7e.png)
Expected behaviour:we can have a 'view all' button under each attribute which will display all the terms listed

**Comment by robiulpro** [comment]
We can implement a dropdown instead of list

**Comment by ashika123** [comment]
Fixed.Verified
