### ISSUE TITLE
On seller page:  move the Brand description to the bottom of the page

### ISSUE THREAD

**Issue by loveleenjoao** [ajency/Coopstore#140]
http://www.coopstore.in/seller/Rosy+Hosiery+Mills+/ 

Here can we move the Text to the bottom of the page, so banner will be showcased well :
example:

Rosy Hosiery Mills

Renka Fashions is the first flagship brand from the stable of Rosy Hosiery Mills, a 54 year old wholesale manufacturing company of high quality knitted garments and fabrics. As a manufacturer, we export to several international retail houses around the globe like Marks & Spencers, Zara etc. and are an established name in the Indian domestic market as well. Essentially comprising winter wear, our products are of high quality and at an affordable price. The Brand Renka is our first retail experiment and is a wholly online

**Comment by avantih** [comment]
I suggest we leave the description at the top. We will be wrapping the text around the logo, so it won't take up as much space below the banner. Putting the description at the bottom of the page might not look very nice. We will have pagination as well.

**Comment by loveleenjoao** [comment]
makes sense.  let us see how it looks.
