### ISSUE TITLE
The sizes in drop down should not be in alphabetical order

### ISSUE THREAD

**Issue by loveleenjoao** [ajency/Coopstore#142]
It should be 
S
M
L
XL

![screenshot](https://cloud.githubusercontent.com/assets/11989661/7201988/845d25fc-e52b-11e4-85ef-a4120729c79c.jpg)

**Comment by ashika123** [comment]
This can be solved by arranging the terms of the attribute size clothing in backend in the required way.
The terms are arranged using drag and drop 
http://www.coopstore.in/wp-admin/edit-tags.php?taxonomy=pa_size-womens-winterwear&post_type=product&paged=3

![size clothing coopstore wordpress](https://cloud.githubusercontent.com/assets/9797052/7223736/c58c6130-e744-11e4-970a-e2f1eeae7a54.png)
