### ISSUE TITLE
Label out of stock has to be displayed when the product is out of stock

### ISSUE THREAD

**Issue by ashika123** [ajency/Coopstore#44]
steps:
Let the product be out of stock

Current behaviour:No label is displayed indicating the product as out of stock
Expected behaviour: When the product is out of stock, a label should indicate the same on the product page

**Comment by avantih** [comment]
Currently, the setting in Woocommerce for 'Out Of Stock Visibility' is "Hide out of stock items from the catalog."
Given the above option, you shouldn't be seeing a product on the site if its is out of stock.

**Comment by ashika123** [comment]
Fixed
