### ISSUE TITLE
Reply and approve a review prompts the admin to rate the product

### ISSUE THREAD

**Issue by ashika123** [ajency/Coopstore#65]
Steps:
1.Review a product by entering your name and email id and review a product (Unregistered user)
2.From the admin login go to dashboard and click on reply
3. After entering the text, click on approve and reply
 current behaviour: A message is displayed to rate the product 
Expected behaviour:There is no clear option available to rate the product and hence cannot 'approve and reply' the product
![review](https://cloud.githubusercontent.com/assets/9797052/6845873/12a90686-d3df-11e4-97fb-7a0a15dad5af.png)

**Comment by anujkhurana** [comment]
Reviews are not needed. Can be removed from the site.

**Comment by ashika123** [comment]
ok
