### ISSUE TITLE
Using an extra pipe in the image column gives a error message while importing the excel 

### ISSUE THREAD

**Issue by ashika123** [ajency/Coopstore#66]
Steps:
In the image field after entering the image links enter and extra pipe
The link uploaded was 
http://www.coopstoretest.in/wp-content/uploads/2015/03/LG-Google-Nexus-5-16-SDL449311710-1-3c436.jpg|http://n2.sdlcdn.com/imgs/a/j/x/large/LG-Google-Nexus-5-16-SDL449311710-2-ebc2d.jpg|http://n3.sdlcdn.com/imgs/a/p/0/large/LG-Google-Nexus-5-16-SDL449311710-4-2a79d.jpg|

current behaviour: An error message is given on product import and the gallery images in the back end are displayed as shown
![extra pipe](https://cloud.githubusercontent.com/assets/9797052/6846395/101db416-d3e4-11e4-8dac-106f501659e7.png)

**Comment by robiulpro** [comment]
@ashika, why you using extra pipe, as pipe used to seperate multiple
images, remove pipe after last image always.

**Comment by anujkhurana** [comment]
For now we can ignore this bug. But Ashika is right that our import must
prevent user errors.

Woocommerce default import behavior does not handles such errors?

**Comment by robiulpro** [comment]
These are minor error in woocommerce csv import plugin, it doesnot prevent
importing the product.
