### ISSUE TITLE
Product thumbnails are in different sizes 

### ISSUE THREAD

**Issue by ashika123** [ajency/Coopstore#70]
The product thumbnails are of different sizes and hence products are aligned incorrectly
![product thumbnails](https://cloud.githubusercontent.com/assets/9797052/6863475/3c788bdc-d478-11e4-9110-df7fe7edbc1f.png)

**Comment by anujkhurana** [comment]
Robiul discuss this with me. This is usually fixed through theme and
woocommerce settings.
